
[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_functions = test_*
python_classes = Test*
addopts = -v 
markers =
    ui: тесты UI-слоя
    api: тесты API-слоя
norecursedirs = .git __pycache__ allure-results allure-report